version: "2.1"
services:
  source:
    build: .
    command:
      - /bin/true
    volumes:
      - app-static:/opt/app/uchan/view/static

  app:
    build: .
    volumes:
      - ./docker/uwsgi.ini:/etc/uwsgi/uwsgi.ini:ro
      - ./data/log:/opt/app/data/log
      - ./data/media:/opt/app/data/media
    command: app
  worker:
    build: .
    volumes:
      - ./data/log:/opt/app/data/log
    command: worker

  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/media:/opt/app/data/media:ro
      - app-static:/opt/uchanstatic
    depends_on:
      - app

  varnish:
    build: ./docker/varnish
    ports:
      - "${UCHAN_PORT}:80"
    environment:
      - UCHAN_VARNISH_MEMSIZE
    depends_on:
      - nginx
      - app
      - worker

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=uchan
      - POSTGRES_PASSWORD=uchan
    volumes:
      - ./data/database:/var/lib/postgresql/data

  memcached:
    image: memcached:1.4-alpine

  queue:
    image: rabbitmq:alpine

volumes:
  app-static:
