apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uchan.fullname" . }}-media
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.uchan.mediaStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.uchan.mediaStorageSizeRequest }}
