{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uchan.fullname" . }}
  labels:
    {{- include "uchan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uchan.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
